### PR TITLE
Make ipaddress a conditional dependency.  (Closes: #247)

### PR DESCRIPTION
**Pull request by hlieberman**
Note, this requires a build version of setuptools greater than 36.2.

### CODE REVIEW

**Comment by hlieberman** [comment]
I suspect the codecov thing is a false positive; I can't imagine it changing the coverage at all, unless it's measuring the coverage in the dependencies (which would be a bad idea).

**Comment by hlieberman** [comment]
@meejah, it should work, but... documentation on this functionality is, let's say, "sparse".  I'd imagine it would simply either pin/hash the dependency or not, depending on whether you were using py2 or py3.  The PEP doesn't specify the behavior, though, and neither does setuptools' docs.  So, I'm just guessing.

Added the setup_depends!

**Comment by meejah** [comment]
Great, thanks!

(...and yes, in my experience codecov "often" thinks things aren't covered in PRs for some reason I don't care to debug)

**Comment by meejah** [comment]
Merged; thanks for the PR!

**Pull request merged**
