### PR TITLE
merge Tor() API object from release-1.x

### PR DESCRIPTION
**Pull request by meejah**
This adds a top-level API object called Tor() which is created via `connect` or `launch` and is intended to be "the" way to interact with txtorcon for most users.

### CODE REVIEW

**Comment by lwm** [comment]
:beers: :beers: :beers: :beers: :beers: :beers: :beers:

**Comment by meejah** [comment]
note: there *are* docs for this; I'm going to merge the (basically complete doc re-write) after I merge all the new features...

**Comment by meejah** [comment]
hmm, codecov seems confused...is it handling merging coverage from py3 + py2 environments properly?

**Comment by meejah** [comment]
Hmm, interesting: looks like github didn't detect the `--squash` merge I did from the command-line. Anyway, merged.

**Pull request closed without merging**
