### PR TITLE
remove usage of "six"

### PR DESCRIPTION
**Pull request by a-detiste**
https://github.com/meejah/txtorcon/issues/395

### CODE REVIEW

**Review by meejah — APPROVED** [review]
Great, thanks!

**Comment by meejah** [comment]
Hmm, how _am_ I supposed to "edit this PR"? (i.e. it says " Maintainers are allowed to edit this pull request. ")

(I tried pushing to your remote, which I didn't _really_ expect to work, and it didn't!)

In `tox.ini` I added `coverage < 7.0.0 ` because coverage changed something and coverage-lcov doesn't work with it ....

**Comment by a-detiste** [comment]
> Hmm, how am I supposed to "edit this PR"? (i.e. it says " Maintainers are allowed to edit this pull request. ")

I have no idea. I will cherry pick 964a2d9a9498b8943c9060e8bfc38ba0dc5e36d4

**Comment by meejah** [comment]
I also just merged a fix to main ...

**Comment by meejah** [comment]
okay, well I can't explain why coveralls and/or GHA didn't like this when it was "your" PR ... but I merged it as #398 so thanks a lot!

**Comment by a-detiste** [comment]
You're welcome

**Pull request closed without merging**
