### PR TITLE
Issue #146: twisted 15 5 0 compatibility

### PR DESCRIPTION
**Pull request by meejah**

### CODE REVIEW

**Comment by hellais** [comment]
This looks good to me. Any idea when you plan to merge this into master and make a new release?

**Comment by meejah** [comment]
@hellais okay, it's in master now. Yes, I can make a 0.14.2 minor-release with it, too

**Comment by meejah** [comment]
Okay, I made a 0.14.2 release as well; see tor-dev for post.

**Comment by hellais** [comment]
You rock! Thanks a lot!

**Pull request merged**
