### PR TITLE
Add support for NULL control port authentication

### PR DESCRIPTION
**Pull request by david415**
https://github.com/meejah/txtorcon/issues/174

### CODE REVIEW

**Comment by meejah** [comment]
Patch looks fine -- I'm curious why codecov is showing the main block of the `if "NULL"...` as uncovered though ... I'll try locally.

**Comment by meejah** [comment]
Locally, it shows 100% coverage. Thanks for the patch!

**Comment by meejah** [comment]
p.s. do you want to add a note to `releases.rst` before I merge?

**Comment by david415** [comment]
ok i added a note to the releases.rst

**Comment by meejah** [comment]
Perfect, thanks :)

**Pull request merged**
