### PR TITLE
David415 errors build circuit

### PR DESCRIPTION
**Pull request by meejah**
Replaces #299 and #287

### CODE REVIEW

**Comment by meejah** [comment]
@david415 look good? (I closed the other PRs, this is all the stuff from those but squashed into "stuff you did" and "stuff I did" because I didn't want to mess with git any more ;)

**Comment by meejah** [comment]
rebased, and wrote a test for the missing lines -- glad I did because there's a bug ;)

**Comment by david415** [comment]
looks good

**Comment by meejah** [comment]
Hrm...all the python 3.4 builders are sad, but it looks like something generic / some packaging thing...? Any clues?

**Pull request merged**
